In [1]:
import pandas as pd;import numpy as np

In [2]:
df = pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

### Creating a Numpy array

In [4]:
# empty array , values are randomly assigned
emp = np.empty((4,2))
emp

array([[4.65003769e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [5]:
# creating a numpy array from an array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
# creating a 2D array
arr2 = np.array([[1,2,3],[1,5,6]])
arr2.shape

(2, 3)

In [8]:
arr2

array([[1, 2, 3],
       [1, 5, 6]])

In [10]:
# check the dimension of an array
arr2.ndim

2

In [11]:
## Basics


In [16]:
arr = np.array([[2,3,4],[7,3,1],[5,1,2],[5,5,2]])
arr

array([[2, 3, 4],
       [7, 3, 1],
       [5, 1, 2],
       [5, 5, 2]])

In [17]:
arr.shape

(4, 3)

In [18]:
# resize the array
arr2 = arr.reshape(3,4)
arr2

array([[2, 3, 4, 7],
       [3, 1, 5, 1],
       [2, 5, 5, 2]])

In [26]:
# reshaping with only one dimension known

arr
arr.shape

(4, 3)

In [33]:
# -1 means same row, 2 feature
arr3 = arr.reshape(-1,2)
arr3

array([[2, 3],
       [4, 7],
       [3, 1],
       [5, 1],
       [2, 5],
       [5, 2]])

In [34]:
arr3.shape

(6, 2)

In [35]:
print(arr.dtype)

int64


In [36]:
arr.itemsize

8

### some standard matrices

In [37]:
# zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# ones 
ones = np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
full = np.full((2,3),9)
full

array([[9, 9, 9],
       [9, 9, 9]])

In [40]:
# identity matrix
order  = 3
I = np.eye(order)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
## Indexing and slice
arr = np.array([[1,2,3],[4,5,6],[7,1,2]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 2]])

In [42]:
arr[0]

array([1, 2, 3])

In [44]:
arr[1,2]

6

In [45]:
arr[1][2]

6

In [47]:
arr[1:]
# after 1st row

array([[4, 5, 6],
       [7, 1, 2]])

In [48]:
arr[:,1:]

array([[2, 3],
       [5, 6],
       [1, 2]])

In [49]:
arr[:,-2:]

array([[2, 3],
       [5, 6],
       [1, 2]])

In [52]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
1
2


In [53]:
for r in arr:
    for c in r:
        print(c)

1
2
3
4
5
6
7
1
2


### Linspace and arange

In [61]:
# linspace(low, high, count)
# 18 values from 10-100
arr_lin = np.linspace(10, 100, 18)
arr_lin

array([ 10.        ,  15.29411765,  20.58823529,  25.88235294,
        31.17647059,  36.47058824,  41.76470588,  47.05882353,
        52.35294118,  57.64705882,  62.94117647,  68.23529412,
        73.52941176,  78.82352941,  84.11764706,  89.41176471,
        94.70588235, 100.        ])

In [64]:
# start, end, step
ar1 = np.arange(1,101,1)
ar1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [67]:
# reverse order
ar2 = np.arange(10,1,-2)
ar2

array([10,  8,  6,  4,  2])

### Generating Random Numbers/Array

In [69]:
## random number
x = np.random.randint(11)
x

9

In [70]:
x = np.random.randint(low=1,high=30)
x

18

In [115]:
## array of given size

rand_arr = np.random.randint(11, 121, (2,3))
rand_arr

array([[28, 59, 45],
       [30, 79, 56]])

In [119]:
# random number between 0-1
rand_float = np.random.random((3,3))
rand_float

array([[0.92644443, 0.56357818, 0.3833511 ],
       [0.72337823, 0.5077689 , 0.12206809],
       [0.15175644, 0.28765554, 0.49005559]])

In [120]:
# random floats in a range

In [122]:
low=10
high=20

rand_float = np.random.random((3,2))
rand_float = low + rand_float*(high-low)
rand_float

array([[13.84120584, 17.47491143],
       [16.83863174, 11.99763613],
       [13.53290281, 18.59080553]])

In [123]:
# we can use random.uniform()

rand_arr = np.random.uniform(low, high, (2,3))
rand_arr

array([[17.6359212 , 16.14933718, 13.2918072 ],
       [12.16398868, 12.90403895, 19.79524502]])

In [127]:
## random number for normal distribution
# randn doesn't take dimension, it takes dimension as per the shape
rnd = np.random.randn(3,2)
rnd

array([[-0.6855511 , -0.25082671],
       [ 0.87661903, -1.56972983],
       [ 1.24606297,  0.26435113]])

In [125]:
mu = np.mean(rnd)
mu

0.24341859343401784

In [126]:
varr = np.var(rnd)
varr

0.08072411401998492

## 8 Common Matrix Operations

In [128]:
mat=np.array([[2,3,1],[4,5,6],[9,7,3]])

In [130]:
# Transpose of the matrix
mat.T


array([[2, 4, 9],
       [3, 5, 7],
       [1, 6, 3]])

In [131]:
# multiplicative inverse
mat_inv = np.linalg.inv(mat)
mat_inv

array([[-0.49090909, -0.03636364,  0.23636364],
       [ 0.76363636, -0.05454545, -0.14545455],
       [-0.30909091,  0.23636364, -0.03636364]])

In [132]:
mat.shape

(3, 3)

In [133]:
mat_inv.shape

(3, 3)

In [134]:
np.matmul(mat,mat_inv)

array([[1.00000000e+00, 0.00000000e+00, 4.85722573e-17],
       [0.00000000e+00, 1.00000000e+00, 9.71445147e-17],
       [6.66133815e-16, 0.00000000e+00, 1.00000000e+00]])

## 9 Artithmetic operations between matrices


In [135]:
mat

array([[2, 3, 1],
       [4, 5, 6],
       [9, 7, 3]])

In [136]:
# it calculates the transpose of the matrix
mat2 = mat.T
mat2

array([[2, 4, 9],
       [3, 5, 7],
       [1, 6, 3]])

In [137]:
mat+mat2

array([[ 4,  7, 10],
       [ 7, 10, 13],
       [10, 13,  6]])

In [138]:
mat-mat2

array([[ 0, -1, -8],
       [ 1,  0, -1],
       [ 8,  1,  0]])

In [139]:
mat*mat2

array([[ 4, 12,  9],
       [12, 25, 42],
       [ 9, 42,  9]])

In [140]:
np.matmul(mat, mat2)

array([[ 14,  29,  42],
       [ 29,  77,  89],
       [ 42,  89, 139]])

## 10 Arithmetic operations of matrix with a scalar

In [141]:
arr = np.array([10,12,14,15,17,21])
arr

array([10, 12, 14, 15, 17, 21])

In [142]:
arr2 = 10+arr

In [143]:
arr2

array([20, 22, 24, 25, 27, 31])

## 11 Mathematical operation

In [144]:
x = 2.73
ans = np.log(x)
ans

1.0043016091968684

In [145]:
l = [2,3,4,5,6,1,2,73]
np.log(l)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       0.        , 0.69314718, 4.29045944])

In [146]:
x = np.log(2)
ans = np.exp(x)
print(ans)

2.0


In [147]:
l = [np.log(x) for x in range(1,10)]
ans = [np.exp(i) for i in l]
ans

[1.0,
 2.0,
 3.0000000000000004,
 4.0,
 4.999999999999999,
 6.0,
 6.999999999999999,
 7.999999999999998,
 9.000000000000002]

In [148]:
# sin cost tan

factor = [1,2,3,4]
rads = [np.pi/i for i in factor]
rads

[3.141592653589793, 1.5707963267948966, 1.0471975511965976, 0.7853981633974483]

In [149]:
sins = [np.sin(rads)]
sins

[array([1.22464680e-16, 1.00000000e+00, 8.66025404e-01, 7.07106781e-01])]

In [150]:
## statistics
mat

array([[2, 3, 1],
       [4, 5, 6],
       [9, 7, 3]])

In [151]:
print(mat.min())
print(mat.min(axis=0))
print(mat.min(axis=1))

1
[2 3 1]
[1 4 3]


In [152]:
print(mat.var(axis=1))
print(mat.var(axis=0))

[0.66666667 0.66666667 6.22222222]
[8.66666667 2.66666667 4.22222222]


## 13. Concatenating numpy

In [153]:
mat

array([[2, 3, 1],
       [4, 5, 6],
       [9, 7, 3]])

In [154]:
mat2

array([[2, 4, 9],
       [3, 5, 7],
       [1, 6, 3]])

In [159]:
res = np.concatenate((mat, mat2), axis=1)

In [160]:
res

array([[2, 3, 1, 2, 4, 9],
       [4, 5, 6, 3, 5, 7],
       [9, 7, 3, 1, 6, 3]])

In [163]:
res = np.concatenate((mat, mat2), axis=0) # concatenate as row-wise

In [162]:
res

array([[2, 3, 1],
       [4, 5, 6],
       [9, 7, 3],
       [2, 4, 9],
       [3, 5, 7],
       [1, 6, 3]])

In [164]:
np.hstack((mat, mat2))

array([[2, 3, 1, 2, 4, 9],
       [4, 5, 6, 3, 5, 7],
       [9, 7, 3, 1, 6, 3]])

In [165]:
np.vstack((mat,mat2))

array([[2, 3, 1],
       [4, 5, 6],
       [9, 7, 3],
       [2, 4, 9],
       [3, 5, 7],
       [1, 6, 3]])